import {createFileRoute,Link} from "@tanstack/react-router";import{useEffect,useState}from"react";import{adminDashboard,adminView,getAdminToken,setAdminToken}from"@/lib/avant-backend";import{finishAdminMfa,signInAdmin,signOutAdmin}from"@/lib/firebase-admin-auth";
export const Route=createFileRoute("/admin")({component:AdminPage});
function AdminPage(){const[data,setData]=useState<any>(null),[view,setView]=useState("dashboard"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mfa,setMfa]=useState(false),[code,setCode]=useState("");
async function load(v=view){const t=getAdminToken();if(!t)return;setBusy(true);setError("");try{setData(v==="dashboard"?await adminDashboard(t):await adminView(t,v as any));setView(v)}catch(e:any){setAdminToken(null);setError(e.message||"Admin session failed")}finally{setBusy(false)}}
useEffect(()=>{void load("dashboard")},[]);
async function login(){setBusy(true);setError("");try{const r:any=await signInAdmin();if(r.mfaRequired)setMfa(true);else await load("dashboard")}catch(e:any){setError(e.message||"Sign-in failed")}finally{setBusy(false)}}
async function verify(){setBusy(true);setError("");try{await finishAdminMfa(code);setMfa(false);setCode("");await load("dashboard")}catch(e:any){setError(e.message||"Invalid authenticator code")}finally{setBusy(false)}}
if(!getAdminToken()&&!data)return <main className="min-h-screen bg-[#07090D] px-6 py-16 text-white"><section className="mx-auto max-w-md"><Link to="/" className="text-sm text-white/60">← Avant Movies</Link><h1 className="mt-10 text-3xl font-semibold">Admin access</h1><p className="mt-3 text-sm leading-6 text-white/55">Restricted to the authorized Avant super-admin. Google sign-in is verified by Firebase and the backend allowlist.</p>{mfa?<><input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" placeholder="Authenticator code" className="mt-6 w-full rounded border border-white/15 bg-white/5 px-4 py-3"/><button onClick={()=>void verify()} disabled={busy||!code.trim()} className="mt-3 w-full rounded bg-white px-4 py-3 font-medium text-black disabled:opacity-50">Verify code</button></>:<button onClick={()=>void login()} disabled={busy} className="mt-7 w-full rounded bg-white px-4 py-3 font-medium text-black disabled:opacity-50">{busy?"Checking…":"Continue with Google"}</button>}{error&&<p className="mt-4 rounded border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}</section></main>;
const tabs=["dashboard","customers","payments","products","entitlements","audit"];return <main className="min-h-screen bg-[#07090D] px-5 py-10 text-white"><section className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-white/40">Avant Movies</p><h1 className="text-3xl font-semibold">Admin</h1></div><button onClick={()=>void signOutAdmin().then(()=>{setData(null);location.reload()})} className="rounded border border-white/15 px-4 py-2 text-sm">Sign out</button></div><nav className="mt-8 flex flex-wrap gap-2">{tabs.map(t=><button key={t} onClick={()=>void load(t)} className={`rounded px-4 py-2 text-sm ${view===t?"bg-white text-black":"bg-white/5"}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>{error&&<p className="mt-5 text-red-300">{error}</p>}<div className="mt-6 overflow-auto rounded-xl border border-white/10 bg-white/[.03] p-5"><pre className="whitespace-pre-wrap break-words text-xs leading-6 text-white/75">{busy?"Loading…":JSON.stringify(data,null,2)}</pre></div></section></main>}
