import { createFileRoute, Link, useRouter } from '@tanstack/react-router'
import { Smartphone } from 'lucide-react'
import { useEffect, useState } from 'react'
import { resolveCatalogueKey, startPalplussPayment } from '../lib/avant-backend'
import { requireCustomerToken } from '../lib/firebase-customer-auth'
import { productForLegacyContent } from '../lib/backend-catalogue-map'
export const Route=createFileRoute('/checkout/$productId')({component:CheckoutRoute})
function CheckoutRoute(){const{productId}=Route.useParams(),router=useRouter();const[mobile,setMobile]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[product,setProduct]=useState<any>(null);
useEffect(()=>{const mapped=productForLegacyContent(productId)||productId;resolveCatalogueKey(productId).then(x=>setProduct(x.product||null)).catch(()=>{});if(mapped!==productId&&!product)setProduct((p:any)=>p)},[productId]);
async function start(){setBusy(true);setError('');try{const token=await requireCustomerToken();const resolved=product?.id||productForLegacyContent(productId)||productId;const result=await startPalplussPayment(token,{productId:resolved,phone:mobile,idempotencyKey:crypto.randomUUID()});const reference=result.reference||result.payment?.reference;if(!reference)throw new Error(result.message||'Payment was not started.');await router.navigate({to:'/payment/success',search:{reference}})}catch(e:any){setError(e?.message||'Unable to start payment')}finally{setBusy(false)}}
return <main className="min-h-[100svh] bg-[#07090D] px-5 py-12 text-white"><section className="mx-auto max-w-lg"><Link to="/" className="text-sm text-white/60">← Back to Avant</Link><p className="mt-10 text-xs uppercase tracking-[.22em] text-white/45">Secure access</p><h1 className="mt-2 text-4xl font-semibold">Get access</h1>{product&&<div className="mt-6 rounded-lg border border-white/10 bg-white/5 p-4"><p className="font-semibold">{product.name}</p><p className="mt-1 text-sm text-white/55">{product.currency} {(product.price_minor/100).toLocaleString()} · {product.duration_days} days</p></div>}<p className="mt-4 text-sm leading-6 text-white/60">Sign in with Google, enter your M-PESA number, then approve the STK prompt on your phone. Pricing is resolved by the server.</p><input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="M-PESA mobile number" inputMode="tel" autoComplete="tel" className="mt-6 min-h-12 w-full rounded-lg border border-white/10 bg-white/5 px-4"/><button onClick={()=>void start()} disabled={busy||mobile.trim().length<9} className="mt-3 flex min-h-16 w-full items-center gap-4 rounded-lg bg-white px-5 text-left text-black disabled:opacity-50"><Smartphone className="size-5"/><span><strong className="block">{busy?'Starting…':'M-PESA'}</strong><span className="text-sm opacity-65">Pay securely with Palpluss</span></span></button>{error&&<p className="mt-5 rounded-lg border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}</section></main>}
