import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Lock, Play, Share2 } from "lucide-react";
import { StreamingShell } from "@/components/streaming/StreamingShell";
import { resolveCatalogueKey } from "@/lib/avant-backend";
import { publicPageLinks, publicPageMeta, videoObjectSchema } from "@/lib/seo";

export const Route=createFileRoute("/episode/$slug/$episodeNumber")({
  loader:async({params})=>{const n=Number(params.episodeNumber);if(!Number.isInteger(n)||n<1)throw notFound();const data:any=await resolveCatalogueKey(params.slug).catch(()=>null);const title=data?.title;const seasons=data?.seasons||[],episodes=data?.episodes||[];if(!title||title.content_type!=="series")throw notFound();const ordered=[...episodes].sort((a:any,b:any)=>{const sa=seasons.find((s:any)=>s.id===a.season_id)?.season_number||1,sb=seasons.find((s:any)=>s.id===b.season_id)?.season_number||1;return sa-sb||a.episode_number-b.episode_number});const episode=ordered[n-1];if(!episode)throw notFound();return{item:title,episode,episodeNumber:n};},
  head:({loaderData})=>{if(!loaderData)return{};const{item,episode,episodeNumber}=loaderData,path=`/episode/${item.slug}/${episodeNumber}`,title=`${episode.title} — ${item.title} | Avant Movies`,description=episode.description||`Watch ${episode.title} from ${item.title} on Avant Movies.`,image=episode.thumbnail_url||(episode.youtube_video_id?`https://i.ytimg.com/vi/${episode.youtube_video_id}/maxresdefault.jpg`:item.backdrop_url||item.poster_url);return{meta:publicPageMeta(path,title,description,image,"video.episode"),links:publicPageLinks(path),scripts:episode.youtube_video_id?[{type:"application/ld+json",children:JSON.stringify(videoObjectSchema({name:episode.title,description,youtubeId:episode.youtube_video_id,duration:episode.duration_seconds?pageDuration(episode.duration_seconds):undefined,pagePath:path,episodeNumber,seriesName:item.title}))}]:[]}},
  component:EpisodeSharePage,
});
function pageDuration(seconds:number){const m=Math.floor(seconds/60),s=seconds%60;return`${m}:${String(s).padStart(2,"0")}`}
function EpisodeSharePage(){const{item,episode,episodeNumber}=Route.useLoaderData();const key=episode.legacy_key||episode.id;const shareEpisode=async()=>{const path=`/episode/${item.slug}/${episodeNumber}`,url=new URL(path.replace(/^\//,""),document.baseURI).href;try{if(navigator.share)await navigator.share({title:`${episode.title} — ${item.title}`,text:episode.description||`Watch ${episode.title} from ${item.title} on Avant Movies.`,url});else{await navigator.clipboard.writeText(url);window.alert("Episode link copied.")}}catch(error:any){if(error?.name!=="AbortError")window.alert("Unable to share this episode.")}};const image=episode.thumbnail_url||(episode.youtube_video_id?`https://i.ytimg.com/vi/${episode.youtube_video_id}/maxresdefault.jpg`:item.backdrop_url||item.poster_url);return <StreamingShell><main className="mx-auto min-h-[80vh] max-w-5xl px-5 pb-20 pt-28 sm:px-10"><Link to="/title/$slug" params={{slug:item.slug}} className="text-sm text-white/55 hover:text-white">← {item.title}</Link><section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-surface"><div className="aspect-video bg-black">{image?<img src={image} alt={`${episode.title} thumbnail`} fetchPriority="high" decoding="async" className="size-full object-cover"/>:<div className="grid size-full place-items-center text-white/30">Avant Movies</div>}</div><div className="p-5 sm:p-8"><p className="eyebrow">{item.title} · Episode {episodeNumber}</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{episode.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">{episode.description||`Watch this episode of ${item.title} on Avant Movies.`}</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/watch/$contentId" params={{contentId:key}} className="inline-flex min-h-12 items-center gap-2 rounded-md bg-white px-5 font-bold text-black">{episode.access_required!==false?<Lock className="size-4"/>:<Play className="size-4 fill-current"/>}{episode.access_required!==false?"View access":"Watch episode"}</Link><button type="button" onClick={()=>void shareEpisode()} className="inline-flex min-h-12 items-center gap-2 rounded-md border border-white/20 px-5 font-bold text-white hover:bg-white/10"><Share2 className="size-4"/>Share</button></div></div></section></main></StreamingShell>}
