import {createFileRoute,Link}from'@tanstack/react-router';import{CheckCircle2,Clock3,Home,LoaderCircle,RefreshCw,XCircle}from'lucide-react';import{StreamingShell}from'@/components/streaming/StreamingShell';import{useEffect,useState}from'react';import{paymentStatus,myLibrary,issueAccessCode,recoverPayment,reconcilePayments}from'../lib/avant-backend';import{customerToken}from'../lib/google-auth';
export const Route=createFileRoute('/payment/success')({head:()=>({meta:[{name:'robots',content:'noindex, nofollow'}]}),validateSearch:(s:Record<string,unknown>)=>({reference:typeof s.reference==='string'?s.reference:'',returnTo:typeof s.returnTo==='string'?s.returnTo:'',origin:typeof s.origin==='string'?s.origin:'',originScroll:typeof s.originScroll==='string'?s.originScroll:'0'}),component:PaymentSuccess});
function PaymentSuccess(){const{reference,returnTo,origin}=Route.useSearch();const[watchKey,setWatchKey]=useState(''),[accessCode,setAccessCode]=useState('');const[status,setStatus]=useState<'checking'|'success'|'pending'|'failed'>('checking'),[message,setMessage]=useState('Checking your payment…'),[phone,setPhone]=useState(''),[mpesaCode,setMpesaCode]=useState(''),[recovering,setRecovering]=useState(false),[checks,setChecks]=useState(0);
useEffect(()=>{let stop=false,t:any;async function check(){setChecks(v=>v+1);try{await reconcilePayments().catch(()=>null);const token=await customerToken(false);if(!token){setStatus('failed');setMessage('Sign in with the same Google account used for checkout to verify this payment.');return}const r=await paymentStatus(token,reference);if(stop)return;const s=r.payment?.status;if(['successful','success','completed','complete','paid'].includes(s)||(r.entitlements?.length??0)>0){setStatus('success');setMessage('Payment verified. Your access is active.');try{const issued=await issueAccessCode(r.payment?.id);if(issued?.accessCode)setAccessCode(issued.accessCode)}catch{}try{const lib=await myLibrary(token);const first=lib.continueWatching?.[0]?.legacy_key||lib.entitlements?.find((x:any)=>x.title)?.title?.legacy_key||lib.entitlements?.find((x:any)=>x.title)?.title?.slug||'';setWatchKey(first)}catch{}return}if(s==='failed'||s==='refunded'){setStatus('failed');setMessage('The payment was not completed.');return}setStatus('pending');setMessage('Waiting for M-PESA confirmation…');t=setTimeout(check,3000)}catch(e:any){if(!stop){setStatus('pending');setMessage(e?.message||'Waiting for payment confirmation…');t=setTimeout(check,4000)}}}if(reference)void check();else{setStatus('failed');setMessage('Missing payment reference.')}return()=>{stop=true;clearTimeout(t)}},[reference]);
async function recover(){if(!phone.trim()&&!mpesaCode.trim()){setMessage('Enter the M-PESA phone number or transaction code.');return}setRecovering(true);try{const token=await customerToken(false);if(!token){setStatus('failed');setMessage('Sign in with the same Google account used for checkout.');return}const r=await recoverPayment(token,{phone:phone.trim()||undefined,mpesaCode:mpesaCode.trim()||undefined});if(r.confirmed){setMessage('Payment found. Activating your access…');setStatus('checking');window.location.reload();return}setMessage(r.message||'Payment has not been confirmed yet.')}catch(e:any){setMessage(e?.message||'Unable to verify payment right now.')}finally{setRecovering(false)}}
const pending=status==='checking'||status==='pending';const Icon=status==='success'?CheckCircle2:status==='failed'?XCircle:status==='checking'?LoaderCircle:Clock3;
return <StreamingShell><main className="min-h-[70svh] bg-[#050608] px-4 pb-10 pt-24 text-white sm:pt-28"><section className="mx-auto w-full max-w-md rounded-2xl border border-white/10 bg-[#0d0f13] p-5 text-center shadow-2xl sm:p-7">
 <div className={`mx-auto grid size-12 place-items-center rounded-full border ${status==='success'?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':status==='failed'?'border-red-400/30 bg-red-400/10 text-red-300':'border-white/15 bg-white/5 text-white'}`}><Icon className={`size-6 ${status==='checking'?'animate-spin':''}`}/></div>
 <p className="mt-4 text-[10px] font-bold uppercase tracking-[.2em] text-white/40">Avant Movies · M-PESA</p>
 <h1 className="mt-1 text-2xl font-black">{status==='success'?'Access unlocked':status==='failed'?'Payment not confirmed':'Confirming payment'}</h1>
 <p className="mx-auto mt-2 max-w-sm text-sm leading-5 text-white/55">{message}</p>
 {reference?<div className="mt-4 rounded-xl bg-black/30 px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/35">Payment reference</p><p className="mt-1 break-all font-mono text-xs text-white/60">{reference}</p></div>:null}{accessCode?<div className="mt-3 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-3"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300">Your Avant access code · up to 2 devices</p><p className="mt-2 font-mono text-xl font-black tracking-[.18em] text-white">{accessCode}</p><p className="mt-1 text-[11px] text-white/50">Keep this code. It expires with this subscription.</p></div>:null}
 {pending?<><div className="mt-4 overflow-hidden rounded-full bg-white/5"><div className="h-1 w-2/3 animate-pulse rounded-full bg-white/60"/></div>{checks>=2?<div className="mt-4 rounded-xl border border-white/10 bg-black/25 p-3 text-left"><p className="text-sm font-bold text-white">Already paid?</p><p className="mt-1 text-xs leading-4 text-white/45">Confirm using the M-PESA number or transaction code. You will not be charged again.</p><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="M-PESA phone number" className="mt-3 min-h-11 w-full rounded-lg border border-white/15 bg-black/40 px-3 text-sm outline-none"/><input value={mpesaCode} onChange={e=>setMpesaCode(e.target.value.toUpperCase())} autoCapitalize="characters" placeholder="M-PESA transaction code" className="mt-2 min-h-11 w-full rounded-lg border border-white/15 bg-black/40 px-3 text-sm outline-none"/><button type="button" onClick={()=>void recover()} disabled={recovering||(!phone.trim()&&!mpesaCode.trim())} className="mt-2 min-h-11 w-full rounded-lg bg-white px-4 text-sm font-bold text-black disabled:opacity-50">{recovering?'Verifying payment…':'Confirm payment'}</button></div>:null}</>:null}
 <div className="mt-5 grid gap-2 sm:grid-cols-2">{status==='success'&&watchKey?<Link to="/watch/$contentId" params={{contentId:watchKey}} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-black">Start watching</Link>:<a href={returnTo||origin||"/movies"} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-black"><Home className="size-4"/>Return to title</a>}{status==='failed'?<a href={returnTo||origin||"/movies"} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/15 px-5 text-sm font-semibold text-white"><RefreshCw className="size-4"/>Back to title</a>:<span className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/10 px-5 text-xs text-white/45">{status==='success'?'Ready to watch':'Keep this page open'}</span>}</div>
 </section></main></StreamingShell>}
