import { Link } from "@tanstack/react-router";
import { LogIn, LogOut, Menu, Search, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { BrandMark } from "@/components/streaming/BrandMark";
import { navLinks } from "@/lib/site-data";
import { cn } from "@/lib/utils";
import { hasAdminSession } from "@/lib/avant-backend";
import { customerSession, signInCustomer, signOutCustomer } from "@/lib/firebase-customer-auth";
export function SiteHeader(){const[open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),[admin,setAdmin]=useState(false),[customer,setCustomer]=useState<any>(null),[authBusy,setAuthBusy]=useState(false);
useEffect(()=>{void hasAdminSession().then(setAdmin);void customerSession().then(setCustomer)},[]);
useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[open]);
useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
async function login(){setAuthBusy(true);try{setCustomer(await signInCustomer())}finally{setAuthBusy(false)}}async function logout(){setAuthBusy(true);try{await signOutCustomer();setCustomer(null)}finally{setAuthBusy(false)}}
return <header className={cn("fixed inset-x-0 top-0 z-50 pt-[env(safe-area-inset-top)] text-foreground transition-all duration-500",scrolled||open?"bg-background/95 shadow-lg backdrop-blur-xl":"bg-gradient-to-b from-black/80 to-transparent")}><div className="flex h-16 items-center gap-8 px-5 sm:px-10 lg:px-14"><Link to="/" aria-label="Avant Movies home"><BrandMark/></Link><nav className="hidden items-center gap-6 md:flex">{navLinks.map(l=><Link key={l.to} to={l.to} className="text-sm font-medium text-foreground/80 transition hover:text-foreground" activeProps={{className:"text-foreground font-semibold"}} activeOptions={{exact:l.to==="/"}}>{l.label}</Link>)}<Link to="/admin" className="text-sm font-medium text-foreground/80 hover:text-foreground">{admin?"Admin":"Admin Login"}</Link></nav><div className="ml-auto flex items-center gap-2"><Link to="/search" className="grid size-11 place-items-center rounded-full transition hover:bg-white/10" aria-label="Search"><Search className="size-5"/></Link>{customer?<div className="hidden items-center gap-2 sm:flex"><span className="inline-flex max-w-40 items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-semibold"><UserRound className="size-4"/><span className="truncate">{customer.name||customer.email}</span></span><button onClick={()=>void logout()} disabled={authBusy} className="grid size-10 place-items-center rounded-full hover:bg-white/10" aria-label="Sign out"><LogOut className="size-4"/></button></div>:<button onClick={()=>void login()} disabled={authBusy} className="hidden min-h-10 items-center gap-2 rounded-md bg-white px-4 text-sm font-bold text-black hover:bg-white/85 sm:inline-flex"><LogIn className="size-4"/>{authBusy?"Signing in…":"Sign in"}</button>}<button className="grid size-11 place-items-center rounded-full md:hidden" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav id="mobile-navigation" className="max-h-[calc(100svh-4rem-env(safe-area-inset-top))] overflow-y-auto border-t border-white/10 bg-background px-5 py-4 shadow-2xl md:hidden">{navLinks.map(l=><Link key={l.to} to={l.to} onClick={()=>setOpen(false)} className="flex min-h-12 items-center rounded-md px-2 text-base font-medium transition hover:bg-white/5">{l.label}</Link>)}{customer?<button onClick={()=>void logout()} className="flex min-h-12 w-full items-center gap-3 rounded-md px-2 text-left text-base font-medium"><LogOut className="size-5"/>Sign out</button>:<button onClick={()=>void login()} className="flex min-h-12 w-full items-center gap-3 rounded-md px-2 text-left text-base font-medium"><LogIn className="size-5"/>Sign in with Google</button>}<Link to="/admin" onClick={()=>setOpen(false)} className="flex min-h-12 items-center rounded-md px-2 text-base font-medium">{admin?"Admin":"Admin Login"}</Link></nav>}</header>}
