import { Link } from "@tanstack/react-router";
import { Check, ChevronDown, Play, Plus, Volume2, VolumeX, X } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import type { CatalogueTitle } from "@/lib/site-data";
import { readMyList, toggleMyList } from "@/lib/my-list";
import { customerToken, requireCustomerToken } from "@/lib/google-auth";
import { youtubeEmbedUrl } from "@/lib/video-embeds";

export function TitlePreviewModal({item,onClose}:{item:CatalogueTitle;onClose:()=>void}){
 const [saved,setSaved]=useState(()=>readMyList().includes(item.id)); const [muted,setMuted]=useState(false); const [season,setSeason]=useState(item.episodes?.[0]?.season??1); const [closing,setClosing]=useState(false);
 const episodes=item.episodes?.filter(e=>(e.season??1)===season)??[]; const seasons=[...new Set(item.episodes?.map(e=>e.season??1)??[])];
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=(e:KeyboardEvent)=>e.key==="Escape"&&requestClose();addEventListener("keydown",key);return()=>{document.body.style.overflow=old;removeEventListener("keydown",key)}},[onClose]);
 const requestClose=()=>{if(closing)return;setClosing(true);window.setTimeout(onClose,220)};
 const toggleSaved=async()=>{const token=await customerToken(false);if(!token){try{await requireCustomerToken()}catch{return}}setSaved(toggleMyList(item.id).includes(item.id))};
 const start=0,end=Math.min(120,Math.max(30,item.previewDuration??120)); const video=!closing&&item.previewYoutubeId?youtubeEmbedUrl(item.previewYoutubeId,{autoplay:true,muted,controls:false,start,end,loop:true}):null;
 const content=<div className={`avant-preview-backdrop ${closing?"is-closing":""} fixed inset-0 z-[100] overflow-y-auto bg-black/75 backdrop-blur-[2px]`} onMouseDown={e=>{if(e.target===e.currentTarget)requestClose()}}>
  <div className={`avant-preview-dialog ${closing?"is-closing":""} relative mx-auto my-5 w-[min(94vw,1120px)] overflow-hidden rounded-xl bg-[#181818] shadow-2xl sm:my-10`}>
   <button onClick={requestClose} aria-label="Close" className="absolute right-4 top-4 z-30 grid size-10 place-items-center rounded-full bg-[#181818] text-white"><X/></button>
   <section className="relative aspect-[16/8.7] min-h-[260px] overflow-hidden bg-black sm:min-h-[360px]">
    <img src={item.backdrop||item.artwork} alt="" className="absolute inset-0 size-full object-cover"/>
    {video?<iframe key={String(muted)} src={video} title={item.title+" preview"} allow="autoplay; encrypted-media; picture-in-picture" className="pointer-events-none absolute left-1/2 top-1/2 h-[56.25vw] min-h-full w-[177.78vh] min-w-full -translate-x-1/2 -translate-y-1/2 border-0"/>:null}
    <div className="absolute inset-0 bg-gradient-to-t from-[#181818] via-transparent to-black/10"/>
    <div className="absolute bottom-6 left-5 right-5 z-10 sm:bottom-10 sm:left-16 sm:right-16"><h2 className="max-w-3xl text-3xl font-black uppercase sm:text-6xl">{item.title}</h2><div className="mt-5 flex items-center gap-3">{(()=>{const e=item.episodes?.[0];const free=e?.youtubeId&&e.locked===false;return free?<Link to="/watch/$contentId" params={{contentId:e.legacyKey??item.slug+"-1"}} onClick={requestClose} className="inline-flex min-h-12 items-center gap-2 rounded bg-white px-6 font-bold text-black"><Play className="fill-current"/>Play</Link>:<Link to="/title/$slug" params={{slug:item.slug}} onClick={requestClose} className="inline-flex min-h-12 items-center gap-2 rounded bg-white px-6 font-bold text-black"><Play className="fill-current"/>More Info</Link>})()}<button onClick={()=>void toggleSaved()} className="grid size-12 place-items-center rounded-full border-2 border-white/55">{saved?<Check/>:<Plus/>}</button></div></div>
    {video?<button onClick={()=>setMuted(v=>!v)} className="absolute bottom-6 right-5 z-20 grid size-11 place-items-center rounded-full border border-white/50 bg-black/30 sm:right-16">{muted?<VolumeX/>:<Volume2/>}</button>:null}
   </section>
   <section className="grid gap-6 px-5 pb-7 pt-4 sm:grid-cols-[1.8fr_1fr] sm:gap-8 sm:px-16 sm:pb-8"><div><div className="flex flex-wrap gap-3 font-semibold"><span>{item.year??"Avant"}</span>{item.episodes?<span>{seasons.length>1?seasons.length+" seasons":"1 season"}</span>:null}<span className="rounded border border-white/40 px-1.5">{item.quality??"HD"}</span></div><p className="mt-5 text-base leading-7 text-white/85">{item.synopsis}</p></div><div className="space-y-3 text-sm leading-6">{item.cast?.length?<p><span className="text-white/45">Cast:</span> {item.cast.slice(0,4).join(", ")}</p>:null}<p><span className="text-white/45">Genres:</span> {item.genres.join(", ")}</p>{item.maturityRating?<p><span className="text-white/45">Maturity:</span> {item.maturityRating}</p>:null}</div></section>
   {item.episodes?<section className="px-5 pb-[max(2rem,env(safe-area-inset-bottom))] sm:px-16"><div className="flex items-center justify-between"><h3 className="text-3xl font-bold">Episodes</h3>{seasons.length?<div className="relative"><select value={season} onChange={e=>setSeason(+e.target.value)} className="appearance-none rounded border border-white/30 bg-[#242424] py-3 pl-5 pr-11 font-bold">{seasons.map(s=><option key={s} value={s}>Season {s}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-5 -translate-y-1/2"/></div>:null}</div><div className="mt-5 divide-y divide-white/15">{episodes.map((e,i)=><Link key={e.legacyKey??i} to="/watch/$contentId" params={{contentId:e.legacyKey??item.slug+"-"+(i+1)}} onClick={requestClose} className="grid grid-cols-[1.5rem_6.5rem_minmax(0,1fr)] items-center gap-3 py-4 transition hover:bg-white/5 sm:grid-cols-[3rem_11rem_1fr_auto] sm:gap-4 sm:py-5"><span className="text-center text-2xl text-white/65">{i+1}</span><div className="relative aspect-video overflow-hidden rounded"><img src={e.poster??(e.youtubeId?`https://i.ytimg.com/vi/${e.youtubeId}/hqdefault.jpg`:item.artwork)} className="size-full object-cover"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-10 place-items-center rounded-full border border-white/70 bg-black/40"><Play className="size-5 fill-white"/></span></span></div><div><h4 className="font-bold">{e.title}</h4><p className="mt-1 line-clamp-2 text-sm text-white/55">{e.description}</p></div><span className="hidden text-sm sm:block">{e.duration}</span></Link>)}</div></section>:null}
  </div>
 </div>; return typeof document!=="undefined"?createPortal(content,document.body):null;
}