import { Link } from "@tanstack/react-router";
import { Check, ChevronDown, Play, Plus, Volume2, VolumeX, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { CatalogueTitle } from "@/lib/site-data";
import { freeContentId, isFreeTitle } from "@/lib/catalogue";
import { readMyList, toggleMyList } from "@/lib/my-list";
import { customerToken, requireCustomerToken } from "@/lib/google-auth";
import { youtubeEmbedUrl } from "@/lib/video-embeds";
import { rememberReturnContext } from "@/lib/navigation-memory";
import { accountAccess, cachedSubscriber, subscribeAccessChanged, type AccessState } from "@/lib/avant-backend";

export function TitlePreviewModal({item,onClose}:{item:CatalogueTitle;onClose:()=>void}){
 const frameRef=useRef<HTMLIFrameElement|null>(null); const [previewInView,setPreviewInView]=useState(true); const heroRef=useRef<HTMLElement|null>(null); const [elapsed,setElapsed]=useState(0); const [saved,setSaved]=useState(()=>readMyList().includes(item.id)); const [muted,setMuted]=useState(false); const [season,setSeason]=useState(item.episodes?.[0]?.season??1); const [closing,setClosing]=useState(false); const [accessState,setAccessState]=useState<AccessState>(()=>cachedSubscriber()?"authorized":"loading"); const [accessVersion,setAccessVersion]=useState(0);
 const freeFullTitle=isFreeTitle(item);
 const freeId=freeContentId(item);
 useEffect(()=>subscribeAccessChanged(()=>setAccessVersion(v=>v+1)),[]); useEffect(()=>{let live=true;if(freeFullTitle){setAccessState("authorized");return()=>{live=false}}setAccessState("loading");customerToken(false).then(async token=>{if(!live)return;if(!token){setAccessState("signed_out");return}try{const a=await accountAccess(token);if(live)setAccessState(a.subscriber?"authorized":"locked")}catch{if(live)setAccessState("error")}});return()=>{live=false}},[item.slug,item.episodes?.[0]?.legacyKey,freeFullTitle,accessVersion]);
 const episodes=item.episodes?.filter(e=>(e.season??1)===season)??[]; const seasons=[...new Set(item.episodes?.map(e=>e.season??1)??[])];
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=(e:KeyboardEvent)=>e.key==="Escape"&&requestClose();addEventListener("keydown",key);return()=>{document.body.style.overflow=old;removeEventListener("keydown",key)}},[onClose]);
 const openTitle=()=>{rememberReturnContext("catalogue",item.slug);requestClose()};
 const requestClose=()=>{if(closing)return;setClosing(true);window.setTimeout(onClose,220)};
 const toggleSaved=async()=>{const token=await customerToken(false);if(!token){try{await requireCustomerToken()}catch{return}}setSaved(toggleMyList(item.id).includes(item.id))};
 const start=0,end=60; const [fallbackCycle,setFallbackCycle]=useState(0);
 const dedicatedPreview=item.trailerEmbedUrl||item.previewYoutubeId;
 const fallbackYoutube=item.type==="movie"?item.youtubeVideoId:item.episodes?.[0]?.youtubeId;
 const fallbackVimeo=item.type==="movie"?item.vimeoVideoId:item.episodes?.[0]?.vimeoVideoId;
 const fallbackPreview=!dedicatedPreview&&(fallbackYoutube||fallbackVimeo);
 const video=!closing&&previewInView?(item.trailerEmbedUrl|| (item.previewYoutubeId?youtubeEmbedUrl(item.previewYoutubeId,{autoplay:true,muted,controls:false,loop:true,jsApi:true}):fallbackYoutube?youtubeEmbedUrl(fallbackYoutube,{autoplay:true,muted,controls:false,start:0,end:60,loop:true,jsApi:true}):fallbackVimeo?`https://player.vimeo.com/video/${fallbackVimeo}?autoplay=1&muted=${muted?1:0}&controls=0&dnt=1&title=0&byline=0&portrait=0`:null)):null;
 useEffect(()=>{if(!fallbackPreview)return;setFallbackCycle(0);const t=window.setInterval(()=>setFallbackCycle(v=>v+1),60000);return()=>window.clearInterval(t)},[item.slug,Boolean(fallbackPreview)]);
 useEffect(()=>{if(!video){setElapsed(0);return}
 const receive=(event:MessageEvent)=>{try{const data=typeof event.data==="string"?JSON.parse(event.data):event.data;if(data?.event==="infoDelivery"&&typeof data?.info?.currentTime==="number"){const total=Math.max(1,end-start);const t=Math.max(0,data.info.currentTime-start);setElapsed(t>=total?0:t)}}catch{}};
 window.addEventListener("message",receive);
 const poll=window.setInterval(()=>frameRef.current?.contentWindow?.postMessage(JSON.stringify({event:"listening",id:"avant-preview"}),"*"),500);
 return()=>{window.removeEventListener("message",receive);window.clearInterval(poll)}
 },[video,end,start]);
 useEffect(()=>{const node=heroRef.current;if(!node)return;const ob=new IntersectionObserver(([e])=>{if(!e)return;const visible=e.isIntersecting&&e.intersectionRatio>=.25;setPreviewInView(visible);if(!visible)frameRef.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func:"pauseVideo",args:[]}),"*")},{threshold:[0,.25,.5]});ob.observe(node);return()=>ob.disconnect()},[item.id]);
 const content=<div className={`avant-preview-backdrop ${closing?"is-closing":""} fixed inset-0 z-[100] overflow-y-auto bg-black/82 backdrop-blur-[10px]`} onMouseDown={e=>{if(e.target===e.currentTarget)requestClose()}}>
  <div className={`avant-preview-dialog ${closing?"is-closing":""} relative mx-auto my-0 w-full max-w-[1180px] overflow-hidden rounded-none border border-white/[.07] bg-[#171717] shadow-[0_45px_130px_rgba(0,0,0,.88)] sm:my-8 sm:w-[min(96vw,1180px)] sm:rounded-2xl`}>
   <button onClick={requestClose} aria-label="Close" className="absolute right-3 top-[max(.75rem,env(safe-area-inset-top))] z-30 grid size-11 place-items-center rounded-full border border-white/10 bg-black/70 text-white shadow-lg backdrop-blur-md transition hover:bg-white/15"><X/></button>
   <section ref={heroRef} className="relative aspect-video w-full min-h-0 overflow-hidden bg-black sm:aspect-[16/8.5] sm:min-h-[430px]">
    <img src={item.backdrop||item.artwork} alt="" className="absolute inset-0 size-full scale-[1.01] object-cover"/>
    {video?<iframe ref={frameRef} key={fallbackPreview?`fallback-${item.slug}-${fallbackCycle}-${muted}`:String(muted)} src={video} title={item.title+" preview"} allow="autoplay; encrypted-media; picture-in-picture" onLoad={(event)=>window.dispatchEvent(new CustomEvent("avant:player-started",{detail:{player:event.currentTarget}}))} className="absolute inset-0 size-full border-0 sm:pointer-events-none sm:left-1/2 sm:top-1/2 sm:h-[56.25vw] sm:min-h-full sm:w-[177.78vh] sm:min-w-full sm:-translate-x-1/2 sm:-translate-y-1/2"/>:null}
    <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.28)_0%,transparent_28%,transparent_48%,rgba(23,23,23,.72)_76%,#171717_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,.72)_0%,rgba(0,0,0,.30)_42%,transparent_76%)]"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_35%,transparent_0%,rgba(0,0,0,.06)_35%,rgba(0,0,0,.42)_100%)]"/>
    <div className="absolute bottom-4 left-4 right-16 z-10 sm:bottom-12 sm:left-14 sm:right-14"><h2 className="max-w-3xl text-[clamp(1.55rem,7vw,4.5rem)] font-black uppercase leading-[.92] drop-shadow-[0_4px_18px_rgba(0,0,0,.75)]">{item.title}</h2><div className="mt-3 flex items-center gap-2 sm:mt-5 sm:gap-3">{(()=>{const e=item.episodes?.[0];return freeFullTitle||accessState==="authorized"?<Link to="/watch/$contentId" params={{contentId:freeId??(item.type==="movie"?item.slug:(e?.legacyKey??item.slug+"-1"))}} onClick={requestClose} className="inline-flex min-h-11 items-center gap-2 rounded bg-white px-4 text-sm sm:min-h-12 sm:px-6 sm:text-base font-bold text-black"><Play className="fill-current"/>{freeFullTitle?"Watch Free":"Watch Full Title"}</Link>:<Link to="/title/$slug" params={{slug:item.slug}} onClick={openTitle} className="inline-flex min-h-12 items-center gap-2 rounded bg-white px-6 font-bold text-black"><Play className="fill-current"/>{accessState==="loading"?"Checking…":"Get Access"}</Link>})()}<button onClick={()=>void toggleSaved()} aria-label={saved?"Remove from My List":"Add to My List"} className="grid size-11 place-items-center rounded-full sm:size-12 border-2 border-white/55">{saved?<Check/>:<Plus/>}</button></div></div>
    {video?<><div className="absolute left-3 top-3 z-20 rounded bg-black/55 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.14em] text-white/80 backdrop-blur">{dedicatedPreview?"Trailer / Preview":"1 Minute Preview"}</div><div className="absolute bottom-0 left-0 right-0 z-20 h-1 bg-white/15"><div className="h-full bg-white shadow-[0_0_10px_rgba(255,255,255,.7)] transition-[width] duration-200 ease-linear" style={{width:`${Math.min(100,(elapsed/Math.max(1,end-start))*100)}%`}}/></div><div className="absolute bottom-2 left-3 z-20 hidden rounded bg-black/45 px-2 py-1 text-[10px] font-semibold tabular-nums text-white/70 backdrop-blur sm:left-14">{Math.floor(elapsed/60)}:{String(Math.floor(elapsed%60)).padStart(2,"0")} / {Math.floor((end-start)/60)}:{String(Math.floor((end-start)%60)).padStart(2,"0")}</div><button onClick={()=>setMuted(v=>!v)} className="absolute bottom-3 right-3 z-20 grid size-11 place-items-center rounded-full border border-white/50 bg-black/30 sm:right-16">{muted?<VolumeX/>:<Volume2/>}</button></>:null}
   </section>
   <section className="grid gap-7 px-5 pb-8 pt-6 sm:grid-cols-[1.7fr_1fr] sm:gap-12 sm:px-14 sm:pb-10 sm:pt-8"><div><div className="flex flex-wrap gap-3 font-semibold"><span>{item.year??"Avant"}</span>{item.episodes?<span>{seasons.length>1?seasons.length+" seasons":"1 season"}</span>:null}<span className="rounded border border-white/40 px-1.5">{item.quality??"HD"}</span></div><p className="mt-5 text-base leading-7 text-white/85">{item.synopsis}</p></div><div className="space-y-3 text-sm leading-6">{item.cast?.length?<p><span className="text-white/45">Cast:</span> {item.cast.slice(0,4).join(", ")}</p>:null}<p><span className="text-white/45">Genres:</span> {item.genres.join(", ")}</p>{item.maturityRating?<p><span className="text-white/45">Maturity:</span> {item.maturityRating}</p>:null}</div></section>
   {item.episodes?<section className="px-5 pb-[max(2rem,env(safe-area-inset-bottom))] sm:px-14"><div className="flex items-center justify-between"><h3 className="text-3xl font-bold">Episodes</h3>{seasons.length?<div className="relative"><select value={season} onChange={e=>setSeason(+e.target.value)} className="appearance-none rounded border border-white/30 bg-[#242424] py-3 pl-5 pr-11 font-bold">{seasons.map(s=><option key={s} value={s}>Season {s}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-5 -translate-y-1/2"/></div>:null}</div><div className="mt-5 divide-y divide-white/15">{episodes.map((e,i)=><Link key={e.legacyKey??i} to="/watch/$contentId" params={{contentId:e.legacyKey??item.slug+"-"+(i+1)}} onClick={requestClose} className="grid grid-cols-[1.5rem_6.5rem_minmax(0,1fr)] items-center gap-3 py-4 transition hover:bg-white/5 sm:grid-cols-[3rem_11rem_1fr_auto] sm:gap-4 sm:py-5"><span className="text-center text-2xl text-white/65">{i+1}</span><div className="relative aspect-video overflow-hidden rounded"><img src={e.poster??(e.youtubeId?`https://i.ytimg.com/vi/${e.youtubeId}/hqdefault.jpg`:item.artwork)} className="size-full object-cover"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-10 place-items-center rounded-full border border-white/70 bg-black/40"><Play className="size-5 fill-white"/></span></span></div><div><h4 className="font-bold">{e.title}</h4><p className="mt-1 line-clamp-2 text-sm text-white/55">{e.description}</p></div><span className="hidden text-sm sm:block">{e.duration}</span></Link>)}</div></section>:null}
  </div>
 </div>; return typeof document!=="undefined"?createPortal(content,document.body):null;
}