import { Link } from "@tanstack/react-router";
import { Check, ChevronDown, Play, Plus, Volume2, VolumeX, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { CatalogueTitle } from "@/lib/site-data";
import { freeContentId, isFreeTitle } from "@/lib/catalogue";
import { readMyList, toggleMyList } from "@/lib/my-list";
import { customerToken, requireCustomerToken } from "@/lib/google-auth";
import { pauseEmbeddedPlayer } from "@/lib/video-embeds";
import { claimMedia, stopAllMedia } from "@/lib/media-session";
import { productForTitleSlug } from "@/lib/backend-catalogue-map";
import { rememberReturnContext } from "@/lib/navigation-memory";
import { resolvePlayback, cachedSubscriber, subscribeAccessChanged, type AccessState } from "@/lib/avant-backend";
import { formatWatchTime, getProgress } from "@/lib/watch-progress";
import { episodeLabel, orderedEpisodes } from "@/lib/episodes";
import { catalogue } from "@/lib/site-data";
import { rankedRelatedTitles } from "@/lib/discovery";

export function TitlePreviewModal({item,onClose}:{item:CatalogueTitle;onClose:()=>void}){
 const frameRef=useRef<HTMLIFrameElement|null>(null); const controlsTimer=useRef<number|null>(null); const [controlsVisible,setControlsVisible]=useState(true); const [videoStarted,setVideoStarted]=useState(false); const [heroDetailsVisible,setHeroDetailsVisible]=useState(true); const [travelMode,setTravelMode]=useState(()=>typeof window!=="undefined"&&localStorage.getItem("avant-travel-mode")==="true"); const [previewInView,setPreviewInView]=useState(true); const heroRef=useRef<HTMLElement|null>(null); const [elapsed,setElapsed]=useState(0); const [saved,setSaved]=useState(()=>readMyList().includes(item.id)); const [muted,setMuted]=useState(false); const [season,setSeason]=useState(item.episodes?.[0]?.season??1); const [closing,setClosing]=useState(false); const [accessState,setAccessState]=useState<AccessState>(()=>cachedSubscriber()?"authorized":"loading"); const [accessVersion,setAccessVersion]=useState(0);
 const showControls=()=>{setControlsVisible(true);if(controlsTimer.current)window.clearTimeout(controlsTimer.current);if(videoStarted)controlsTimer.current=window.setTimeout(()=>setControlsVisible(false),8000)};
 useEffect(()=>{setVideoStarted(false);setHeroDetailsVisible(true);showControls();return()=>{if(controlsTimer.current)window.clearTimeout(controlsTimer.current)}},[item.id]);
 const freeFullTitle=isFreeTitle(item);
 const freeId=item.type==="movie"?item.slug:(item.episodes?.[0]?.legacyKey??`${item.slug}-1`);
 useEffect(()=>subscribeAccessChanged(()=>setAccessVersion(v=>v+1)),[]); useEffect(()=>{const sync=(e:any)=>setTravelMode(Boolean(e.detail?.active));window.addEventListener("avant:travel-mode-changed" as any,sync);return()=>window.removeEventListener("avant:travel-mode-changed" as any,sync)},[]); useEffect(()=>{let live=true;if(freeFullTitle){setAccessState("authorized");return()=>{live=false}}setAccessState("loading");customerToken(false).then(async token=>{if(!live)return;try{const e=item.episodes?.[0];const target=item.type==="movie"?item.slug:(e?.legacyKey??item.slug+"-1");const a=await resolvePlayback(token,target);if(live)setAccessState(a?.authorized?"authorized":"locked")}catch(err:any){if(live)setAccessState(err?.status===403?"locked":"error")}});return()=>{live=false}},[item.slug,item.episodes?.[0]?.legacyKey,freeFullTitle,accessVersion]);
 const isSeries=item.type==="series"; const ordered=orderedEpisodes(item); const seasons=isSeries?[...new Set(ordered.map(e=>e.season))]:[]; const episodes=isSeries?ordered.filter(e=>e.season===season):[]; const resumable=ordered.map(e=>({...e,progress:getProgress(e.contentId)})).filter(e=>(e.progress?.seconds??0)>5).sort((a,b)=>(b.progress?.updatedAt??0)-(a.progress?.updatedAt??0))[0]; const primary=resumable??ordered[0]; const titleDuration=item.type==="movie"?(item.episodes?.[0]?.duration||undefined):undefined; const metadata=[item.year,item.type==="movie"?"Film":"Series",item.quality,item.maturityRating,titleDuration].filter(Boolean);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=(e:KeyboardEvent)=>e.key==="Escape"&&requestClose();addEventListener("keydown",key);return()=>{document.body.style.overflow=old;removeEventListener("keydown",key)}},[onClose]);
 const openTitle=()=>{rememberReturnContext("catalogue",item.slug);requestClose()};
 const requestClose=()=>{if(closing)return;pauseEmbeddedPlayer(frameRef.current);stopAllMedia();setClosing(true);window.setTimeout(onClose,220)};
 const toggleSaved=async()=>{const token=await customerToken(false);if(!token){try{await requireCustomerToken()}catch{return}}setSaved(toggleMyList(item.id).includes(item.id))};
 const start=0,end=60; const [fallbackCycle,setFallbackCycle]=useState(0); const resumeAtRef=useRef(0);
 const dedicatedPreview=item.trailerEmbedUrl||item.previewVimeoVideoId;
 const fallbackVimeo=freeFullTitle?(item.type==="movie"?item.vimeoVideoId:item.episodes?.[0]?.vimeoVideoId):undefined;
 const fallbackPreview=!dedicatedPreview&&fallbackVimeo;
 const normalizedDedicatedPreview=(()=>{if(!item.trailerEmbedUrl)return null;try{const u=new URL(item.trailerEmbedUrl);if(!u.hostname.includes("vimeo"))return null;u.searchParams.set("autoplay","1");u.searchParams.set("muted",muted?"1":"0");u.searchParams.delete("background");u.searchParams.set("controls","1");u.searchParams.set("playsinline","1");return u.toString()}catch{return null}})();
 const previewVimeo=item.previewVimeoVideoId;
 const video=!travelMode&&!closing?(normalizedDedicatedPreview||(previewVimeo?`https://player.vimeo.com/video/${previewVimeo}?autoplay=1&muted=${muted?1:0}&controls=1`:fallbackVimeo?`https://player.vimeo.com/video/${fallbackVimeo}?autoplay=1&muted=${muted?1:0}&controls=1`:null)):null;
 useEffect(()=>{if(!fallbackPreview)return;setFallbackCycle(0);const t=window.setInterval(()=>setFallbackCycle(v=>v+1),60000);return()=>window.clearInterval(t)},[item.slug,Boolean(fallbackPreview)]);
 useEffect(()=>{if(!video){setElapsed(0);return}
 const commandPreview=(method:string,value?:number)=>frameRef.current?.contentWindow?.postMessage(value===undefined?{method}:{method,value},"*");
 const receive=(event:MessageEvent)=>{try{const data=typeof event.data==="string"?JSON.parse(event.data):event.data;if(data?.event==="infoDelivery"&&typeof data?.info?.currentTime==="number"){const total=Math.max(1,end-start);const t=Math.max(0,data.info.currentTime-start);setElapsed(t>=total?0:t);if(t>0&&!videoStarted){setVideoStarted(true);setControlsVisible(true)}if(t>=2.5)setHeroDetailsVisible(false);if(t>=total){commandPreview("pause");setElapsed(total)}}}catch{}};
 window.addEventListener("message",receive);
 const poll=window.setInterval(()=>frameRef.current?.contentWindow?.postMessage(JSON.stringify({event:"listening",id:"avant-preview"}),"*"),500);
 return()=>{window.removeEventListener("message",receive);window.clearInterval(poll)}
 },[video,end,start,videoStarted]);
 useEffect(()=>{const node=heroRef.current;if(!node)return;let wasVisible=true;const command=(func:string,args:any[]=[])=>frameRef.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func,args}),"*");const vimeo=(method:string,value?:number)=>frameRef.current?.contentWindow?.postMessage(value===undefined?{method}:{method,value},"*");const ob=new IntersectionObserver(([e])=>{if(!e)return;const visible=e.isIntersecting&&e.intersectionRatio>=.25;setPreviewInView(visible);if(!visible){resumeAtRef.current=elapsed;setControlsVisible(false);if(controlsTimer.current)window.clearTimeout(controlsTimer.current);command("pauseVideo");vimeo("pause")}else if(!wasVisible){const resume=Math.max(start,resumeAtRef.current||elapsed);command("seekTo",[resume,true]);command("playVideo");vimeo("setCurrentTime",resume);vimeo("play");showControls()}wasVisible=visible},{threshold:[0,.1,.25,.5,.75]});ob.observe(node);return()=>ob.disconnect()},[item.id,elapsed,start]);
 const recommendations=rankedRelatedTitles(item,catalogue.filter(t=>t.available!==false),4);
 const content=<div className={`avant-preview-backdrop ${closing?"is-closing":""} fixed inset-0 z-[100] overflow-y-auto bg-black/82 backdrop-blur-[10px]`} onMouseDown={e=>{if(e.target===e.currentTarget)requestClose()}}>
  <div className={`avant-preview-dialog ${closing?"is-closing":""} relative mx-auto my-0 w-full max-w-[1180px] overflow-hidden rounded-none border border-white/[.07] bg-[#171717] shadow-[0_45px_130px_rgba(0,0,0,.88)] sm:my-8 sm:w-[min(96vw,1180px)] sm:rounded-2xl`}>
    <button onClick={requestClose} autoFocus aria-label="Close" className="absolute right-3 top-[max(.75rem,env(safe-area-inset-top))] z-30 grid size-11 place-items-center rounded-full border border-white/10 bg-black/70 text-white shadow-lg backdrop-blur-md transition hover:bg-white/15"><X/></button>
   <section ref={heroRef} onPointerDown={showControls} onPointerMove={(e)=>{if(e.pointerType==="mouse")showControls()}} className="relative aspect-video w-full min-h-0 overflow-hidden bg-black sm:aspect-[16/8.5] sm:min-h-[430px]">
    {!video?<img src={item.backdrop||item.artwork} alt="" className="absolute inset-0 size-full scale-[1.01] object-cover"/>:<div className="absolute inset-0 bg-black"/>}
    {video?<><iframe ref={frameRef} key={fallbackPreview?`fallback-${item.slug}-${fallbackCycle}-${muted}`:String(muted)} src={video} title={item.title+" preview"} allow="autoplay; encrypted-media; picture-in-picture" onLoad={(event)=>{claimMedia(event.currentTarget);window.dispatchEvent(new CustomEvent("avant:player-started",{detail:{player:event.currentTarget}}))}} className="absolute inset-0 size-full border-0" referrerPolicy="strict-origin-when-cross-origin"/><button type="button" aria-label="Show preview controls" onClick={showControls} className="absolute inset-0 z-[5] cursor-default bg-transparent"/></>:null}
    <div className={`pointer-events-none absolute inset-0 transition-opacity duration-500 ${controlsVisible?"opacity-100":"opacity-0"}`}><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.28)_0%,transparent_28%,transparent_48%,rgba(23,23,23,.72)_76%,#171717_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,.72)_0%,rgba(0,0,0,.30)_42%,transparent_76%)]"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_35%,transparent_0%,rgba(0,0,0,.06)_35%,rgba(0,0,0,.42)_100%)]"/></div>
     <div className={`absolute bottom-5 left-5 right-20 z-10 transition-all duration-500 sm:bottom-12 sm:left-14 sm:right-14 ${heroDetailsVisible?"translate-y-0 opacity-100":"pointer-events-none translate-y-2 opacity-0"}`}><h2 className="max-w-3xl text-[clamp(1.45rem,6vw,4.5rem)] font-black uppercase leading-[.98] tracking-[-.025em] drop-shadow-[0_4px_18px_rgba(0,0,0,.75)]">{item.title}</h2><div className="mt-4 flex flex-wrap items-center gap-2.5 sm:mt-5 sm:gap-3">{(()=>{const e=item.episodes?.[0];return freeFullTitle||accessState==="authorized"?<Link to="/watch/$contentId" params={{contentId:freeId??(item.type==="movie"?item.slug:(e?.legacyKey??item.slug+"-1"))}} onClick={requestClose} className="inline-flex min-h-11 max-w-[calc(100%-3.5rem)] items-center gap-2 rounded bg-white px-4 text-sm sm:min-h-12 sm:max-w-none sm:px-6 sm:text-base font-bold text-black"><Play className="fill-current"/>{freeFullTitle?(item.type==="series"?"Watch Free Episode":"Watch Free"):"Watch Full Title"}</Link>:<Link to="/checkout/$productId" params={{productId:productForTitleSlug(item.slug)||item.slug}} search={{returnTo:`/title/${item.slug}`,origin:"/",originScroll:"0"}} onClick={requestClose} className="inline-flex min-h-12 items-center gap-2 rounded bg-white px-6 font-bold text-black"><Play className="fill-current"/>{accessState==="loading"?"Checking…":"Get Access"}</Link>})()}<button onClick={()=>void toggleSaved()} aria-label={saved?"Remove from My List":"Add to My List"} className="grid size-11 shrink-0 place-items-center rounded-full sm:size-12 border-2 border-white/55 transition active:scale-90 hover:bg-white/10">{saved?<Check/>:<Plus/>}</button></div></div>
    {video?<><div className={`absolute left-3 top-3 z-20 rounded bg-black/55 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.14em] text-white/80 backdrop-blur transition-opacity duration-500 ${controlsVisible?"opacity-100":"pointer-events-none opacity-0"}`}>{dedicatedPreview?"Trailer / Preview":"1 Minute Preview"}</div><div className={`absolute bottom-0 left-0 right-0 z-20 h-1 bg-white/15 transition-opacity duration-500 ${controlsVisible?"opacity-100":"opacity-0"}`}><div className="h-full bg-white shadow-[0_0_10px_rgba(255,255,255,.7)] transition-[width] duration-200 ease-linear" style={{width:`${Math.min(100,(elapsed/Math.max(1,end-start))*100)}%`}}/></div><div className={`absolute bottom-2 left-3 z-20 hidden rounded bg-black/45 px-2 py-1 text-[10px] font-semibold tabular-nums text-white/70 backdrop-blur transition-opacity duration-500 sm:left-14 ${controlsVisible?"sm:block sm:opacity-100":"sm:pointer-events-none sm:block sm:opacity-0"}`}>{Math.floor(elapsed/60)}:{String(Math.floor(elapsed%60)).padStart(2,"0")} / {Math.floor((end-start)/60)}:{String(Math.floor((end-start)%60)).padStart(2,"0")}</div><button onClick={()=>{showControls();setMuted(v=>!v)}} className={`absolute bottom-3 right-3 z-20 grid size-11 place-items-center rounded-full border border-white/50 bg-black/30 transition-all duration-500 sm:right-16 ${controlsVisible?"scale-100 opacity-100":"pointer-events-none scale-95 opacity-0"}`}>{muted?<VolumeX/>:<Volume2/>}</button></>:null}
   </section>
   <section className="grid gap-5 px-5 pb-7 pt-5 sm:grid-cols-[1.7fr_1fr] sm:gap-12 sm:px-14 sm:pb-10 sm:pt-8"><div><div className="flex flex-wrap items-center gap-x-2 gap-y-2 text-sm font-semibold text-white/75">{metadata.map((value,i)=><span key={String(value)} className="flex items-center gap-2">{i>0?<span className="text-white/25">•</span>:null}<span className={value===item.quality?"rounded border border-white/35 px-1.5 py-0.5":""}>{value}</span></span>)}{isSeries&&item.episodes?.length?<><span className="text-white/25">•</span><span>{seasons.length>1?seasons.length+" seasons":"1 season"} · {item.episodes.length} episodes</span></>:null}</div><p className="mt-4 max-w-3xl text-[15px] leading-6 text-white/85 sm:mt-5 sm:text-base sm:leading-7">{item.synopsis||item.shortDescription}</p>{resumable?<p className="mt-3 text-xs font-semibold text-white/50">Continue {episodeLabel(resumable.episode,resumable.episodeNumber)} · {formatWatchTime(resumable.progress!.seconds)} watched</p>:null}</div><dl className="space-y-2 text-sm leading-6">{item.directors?.length?<div><dt className="inline text-white/45">Director: </dt><dd className="inline">{item.directors.join(", ")}</dd></div>:null}{item.creators?.length?<div><dt className="inline text-white/45">Created by: </dt><dd className="inline">{item.creators.join(", ")}</dd></div>:null}{item.cast?.length?<div><dt className="inline text-white/45">Cast: </dt><dd className="inline">{item.cast.slice(0,6).join(", ")}</dd></div>:null}{item.genres?.length?<div><dt className="inline text-white/45">Genres: </dt><dd className="inline">{item.genres.join(", ")}</dd></div>:null}{item.languages?.length?<div><dt className="inline text-white/45">Languages: </dt><dd className="inline">{item.languages.join(", ")}</dd></div>:null}{item.countries?.length?<div><dt className="inline text-white/45">Country: </dt><dd className="inline">{item.countries.join(", ")}</dd></div>:null}</dl></section>
   {isSeries&&item.episodes?.length?<section className="px-5 pb-[max(2rem,env(safe-area-inset-bottom))] sm:px-14"><div className="flex items-end justify-between gap-4 border-t border-white/10 pt-7"><div><h3 className="text-2xl font-bold sm:text-3xl">Episodes</h3><p className="mt-1 text-xs text-white/45">Season {season} · {episodes.length} episodes</p></div>{seasons.length?<div className="relative"><select value={season} onChange={e=>setSeason(+e.target.value)} className="appearance-none rounded-lg border border-white/25 bg-[#242424] py-2.5 pl-4 pr-10 text-sm font-bold sm:py-3 sm:pl-5 sm:pr-11 sm:text-base">{seasons.map(s=><option key={s} value={s}>Season {s}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-5 -translate-y-1/2"/></div>:null}</div><div className="mt-4 divide-y divide-white/10">{episodes.map(({episode:e,episodeNumber,contentId})=>{const progress=getProgress(contentId);const percent=progress?.duration?Math.min(100,progress.seconds/progress.duration*100):0;return <Link key={contentId} to="/watch/$contentId" params={{contentId}} onClick={requestClose} className="grid grid-cols-[1.4rem_6.8rem_minmax(0,1fr)] items-center gap-3 py-4 transition hover:bg-white/[.035] sm:grid-cols-[3rem_11rem_1fr_auto] sm:gap-4 sm:py-5"><span className="text-center text-xl text-white/55">{episodeNumber}</span><div className="relative aspect-video overflow-hidden rounded bg-black"><img src={e.poster??item.artwork} alt="" loading="lazy" className="size-full object-cover"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-9 place-items-center rounded-full border border-white/70 bg-black/45"><Play className="size-4 fill-white"/></span></span>{percent>0?<span className="absolute inset-x-0 bottom-0 h-1 bg-white/20"><span className="block h-full bg-[#e48b4a]" style={{width:`${percent}%`}}/></span>:null}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#e9a46f]">{episodeLabel(e,episodeNumber)}</p><h4 className="mt-1 line-clamp-1 font-bold">{e.title.replace(/^.*?Episode \d+\s*[—-]?\s*/, "")||`Episode ${episodeNumber}`}</h4>{e.description?<p className="mt-1 line-clamp-2 text-xs leading-5 text-white/55 sm:text-sm">{e.description}</p>:null}{progress?.seconds?<p className="mt-1 text-[11px] font-semibold text-white/45">Resume at {formatWatchTime(progress.seconds)}</p>:null}</div><span className="hidden text-sm text-white/60 sm:block">{e.duration}</span></Link>})}</div></section>:null}
   {recommendations.length?<section className="border-t border-white/10 px-5 pb-[max(2rem,env(safe-area-inset-bottom))] pt-7 sm:px-14"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#e9a46f]">Avant discovery</p><h3 className="mt-1 text-2xl font-black">More Like This on Avant</h3></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{recommendations.map(({title:r,reason})=><Link key={r.id} to="/title/$slug" params={{slug:r.slug}} onClick={requestClose} className="group overflow-hidden rounded-lg border border-white/[.07] bg-white/[.035]"><div className="aspect-video overflow-hidden bg-black"><img src={r.artwork} alt="" loading="lazy" className="size-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-3"><h4 className="line-clamp-1 font-bold">{r.title}</h4><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-[#e9a46f]/75">{reason}</p></div></Link>)}</div></section>:null}
   {item.storyWorld&&((item.storyWorld.characters?.length??0)>0||(item.storyWorld.gallery?.length??0)>0||(item.storyWorld.behindTheScenes?.length??0)>0||(item.storyWorld.extras?.length??0)>0)?<section className="border-t border-white/10 px-5 py-7 sm:px-14"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#e9a46f]">Beyond the screen</p><h3 className="mt-1 text-2xl font-black">Story World</h3>{item.storyWorld.characters?.length?<div className="mt-5"><h4 className="text-sm font-bold">Cast & Characters</h4><div className="mt-3 flex gap-3 overflow-x-auto pb-2 [scrollbar-width:none]">{item.storyWorld.characters.map(person=><article key={person.actor+"-"+person.name} className="w-32 shrink-0 overflow-hidden rounded-lg bg-white/[.04]">{person.image?<img src={person.image} alt={person.actor} loading="lazy" className="aspect-[4/5] w-full object-cover"/>:null}<div className="p-2"><p className="line-clamp-1 text-sm font-bold">{person.actor}</p>{person.name?<p className="line-clamp-1 text-[10px] text-white/45">{person.name}</p>:null}</div></article>)}</div></div>:null}{item.storyWorld.gallery?.length?<div className="mt-5"><h4 className="text-sm font-bold">Official Gallery</h4><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{item.storyWorld.gallery.slice(0,6).map(image=><img key={image.url} src={image.url} alt={image.caption||item.title+" gallery"} loading="lazy" decoding="async" className="aspect-video w-full rounded-lg object-cover"/>)}</div></div>:null}{item.storyWorld.behindTheScenes?.length?<div className="mt-5"><h4 className="text-sm font-bold">Behind the Scenes</h4><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.storyWorld.behindTheScenes.map(extra=><a key={extra.url} href={extra.url} target="_blank" rel="noreferrer" className="rounded-lg border border-white/[.07] bg-white/[.03] p-3"><p className="font-bold">{extra.title}</p>{extra.description?<p className="mt-1 line-clamp-2 text-xs text-white/45">{extra.description}</p>:null}</a>)}</div></div>:null}{item.storyWorld.extras?.length?<div className="mt-5"><h4 className="text-sm font-bold">Extras</h4><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.storyWorld.extras.map(extra=><a key={extra.url} href={extra.url} target="_blank" rel="noreferrer" className="rounded-lg border border-white/[.07] bg-white/[.03] p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#e9a46f]">{extra.kind||"Extra"}</p><p className="mt-1 font-bold">{extra.title}</p></a>)}</div></div>:null}</section>:null}
   <section className="border-t border-white/10 px-5 py-7 sm:px-14"><p className="text-[10px] font-black uppercase tracking-[.16em] text-white/35">About</p><h3 className="mt-1 text-2xl font-black">About {item.title}</h3><div className="mt-4 grid gap-5 text-sm sm:grid-cols-[1.6fr_1fr]"><p className="leading-6 text-white/65">{item.synopsis||item.shortDescription}</p><dl className="space-y-2">{item.directors?.length?<div><dt className="inline text-white/35">Director: </dt><dd className="inline">{item.directors.join(", ")}</dd></div>:null}{item.creators?.length?<div><dt className="inline text-white/35">Created by: </dt><dd className="inline">{item.creators.join(", ")}</dd></div>:null}{item.cast?.length?<div><dt className="inline text-white/35">Cast: </dt><dd className="inline">{item.cast.join(", ")}</dd></div>:null}{item.genres?.length?<div><dt className="inline text-white/35">Genres: </dt><dd className="inline">{item.genres.join(", ")}</dd></div>:null}{item.languages?.length?<div><dt className="inline text-white/35">Languages: </dt><dd className="inline">{item.languages.join(", ")}</dd></div>:null}{item.countries?.length?<div><dt className="inline text-white/35">Country: </dt><dd className="inline">{item.countries.join(", ")}</dd></div>:null}{item.year?<div><dt className="inline text-white/35">Release: </dt><dd className="inline">{item.year}</dd></div>:null}</dl></div></section>
  </div>
 </div>; return typeof document!=="undefined"?createPortal(content,document.body):null;
}