/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TvShowsRouteImport } from './routes/tv-shows'
import { Route as WatchFreeRouteImport } from './routes/watch-free'
import { Route as AdminSectionRouteImport } from './routes/admin_.$section'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as GenreGenreRouteImport } from './routes/genre.$genre'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PersonPersonRouteImport } from './routes/person.$person'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as WatchContentIdRouteImport } from './routes/watch.$contentId'
import { Route as EpisodeSlugEpisodeNumberRouteImport } from './routes/episode.$slug.$episodeNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchFreeRoute = WatchFreeRouteImport.update({
  id: '/watch-free',
  path: '/watch-free',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin_/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreRoute = GenreGenreRouteImport.update({
  id: '/genre/$genre',
  path: '/genre/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonPersonRoute = PersonPersonRouteImport.update({
  id: '/person/$person',
  path: '/person/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchContentIdRoute = WatchContentIdRouteImport.update({
  id: '/watch/$contentId',
  path: '/watch/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeSlugEpisodeNumberRoute =
  EpisodeSlugEpisodeNumberRouteImport.update({
    id: '/episode/$slug/$episodeNumber',
    path: '/episode/$slug/$episodeNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/admin/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/genre/$genre': typeof GenreGenreRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/person/$person': typeof PersonPersonRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/admin/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/genre/$genre': typeof GenreGenreRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/person/$person': typeof PersonPersonRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/admin_/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/genre/$genre': typeof GenreGenreRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/person/$person': typeof PersonPersonRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/tv-shows'
    | '/watch-free'
    | '/admin/$section'
    | '/checkout/$productId'
    | '/genre/$genre'
    | '/payment/failed'
    | '/payment/success'
    | '/person/$person'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/tv-shows'
    | '/watch-free'
    | '/admin/$section'
    | '/checkout/$productId'
    | '/genre/$genre'
    | '/payment/failed'
    | '/payment/success'
    | '/person/$person'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/tv-shows'
    | '/watch-free'
    | '/admin_/$section'
    | '/checkout/$productId'
    | '/genre/$genre'
    | '/payment/failed'
    | '/payment/success'
    | '/person/$person'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  TvShowsRoute: typeof TvShowsRoute
  WatchFreeRoute: typeof WatchFreeRoute
  AdminSectionRoute: typeof AdminSectionRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  GenreGenreRoute: typeof GenreGenreRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PersonPersonRoute: typeof PersonPersonRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchContentIdRoute: typeof WatchContentIdRoute
  EpisodeSlugEpisodeNumberRoute: typeof EpisodeSlugEpisodeNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-free': {
      id: '/watch-free'
      path: '/watch-free'
      fullPath: '/watch-free'
      preLoaderRoute: typeof WatchFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$section': {
      id: '/admin_/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genre': {
      id: '/genre/$genre'
      path: '/genre/$genre'
      fullPath: '/genre/$genre'
      preLoaderRoute: typeof GenreGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$person': {
      id: '/person/$person'
      path: '/person/$person'
      fullPath: '/person/$person'
      preLoaderRoute: typeof PersonPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$contentId': {
      id: '/watch/$contentId'
      path: '/watch/$contentId'
      fullPath: '/watch/$contentId'
      preLoaderRoute: typeof WatchContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$slug/$episodeNumber': {
      id: '/episode/$slug/$episodeNumber'
      path: '/episode/$slug/$episodeNumber'
      fullPath: '/episode/$slug/$episodeNumber'
      preLoaderRoute: typeof EpisodeSlugEpisodeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  TvShowsRoute: TvShowsRoute,
  WatchFreeRoute: WatchFreeRoute,
  AdminSectionRoute: AdminSectionRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  GenreGenreRoute: GenreGenreRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PersonPersonRoute: PersonPersonRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchContentIdRoute: WatchContentIdRoute,
  EpisodeSlugEpisodeNumberRoute: EpisodeSlugEpisodeNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
