/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ABetterLifeRouteImport } from './routes/a-better-life'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BackToUsRouteImport } from './routes/back-to-us'
import { Route as BetterDaysRouteImport } from './routes/better-days'
import { Route as BetterlifeEpisodesRouteImport } from './routes/betterlife-episodes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as NairobbyRouteImport } from './routes/nairobby'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThisIsLifeRouteImport } from './routes/this-is-life'
import { Route as ThisIsLifeEpisodesRouteImport } from './routes/this-is-life-episodes'
import { Route as TvShowsRouteImport } from './routes/tv-shows'
import { Route as WatchFreeRouteImport } from './routes/watch-free'
import { Route as WatchThemAllRouteImport } from './routes/watch-them-all'
import { Route as WriteLikeAMasterRouteImport } from './routes/write-like-a-master'
import { Route as AdminSectionRouteImport } from './routes/admin_.$section'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as WatchContentIdRouteImport } from './routes/watch.$contentId'
import { Route as EpisodeSlugEpisodeNumberRouteImport } from './routes/episode.$slug.$episodeNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ABetterLifeRoute = ABetterLifeRouteImport.update({
  id: '/a-better-life',
  path: '/a-better-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BackToUsRoute = BackToUsRouteImport.update({
  id: '/back-to-us',
  path: '/back-to-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterDaysRoute = BetterDaysRouteImport.update({
  id: '/better-days',
  path: '/better-days',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterlifeEpisodesRoute = BetterlifeEpisodesRouteImport.update({
  id: '/betterlife-episodes',
  path: '/betterlife-episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const NairobbyRoute = NairobbyRouteImport.update({
  id: '/nairobby',
  path: '/nairobby',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisIsLifeRoute = ThisIsLifeRouteImport.update({
  id: '/this-is-life',
  path: '/this-is-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisIsLifeEpisodesRoute = ThisIsLifeEpisodesRouteImport.update({
  id: '/this-is-life-episodes',
  path: '/this-is-life-episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchFreeRoute = WatchFreeRouteImport.update({
  id: '/watch-free',
  path: '/watch-free',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchThemAllRoute = WatchThemAllRouteImport.update({
  id: '/watch-them-all',
  path: '/watch-them-all',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteLikeAMasterRoute = WriteLikeAMasterRouteImport.update({
  id: '/write-like-a-master',
  path: '/write-like-a-master',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin_/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchContentIdRoute = WatchContentIdRouteImport.update({
  id: '/watch/$contentId',
  path: '/watch/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeSlugEpisodeNumberRoute =
  EpisodeSlugEpisodeNumberRouteImport.update({
    id: '/episode/$slug/$episodeNumber',
    path: '/episode/$slug/$episodeNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a-better-life': typeof ABetterLifeRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/back-to-us': typeof BackToUsRoute
  '/better-days': typeof BetterDaysRoute
  '/betterlife-episodes': typeof BetterlifeEpisodesRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/nairobby': typeof NairobbyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/this-is-life': typeof ThisIsLifeRoute
  '/this-is-life-episodes': typeof ThisIsLifeEpisodesRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/watch-them-all': typeof WatchThemAllRoute
  '/write-like-a-master': typeof WriteLikeAMasterRoute
  '/admin/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a-better-life': typeof ABetterLifeRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/back-to-us': typeof BackToUsRoute
  '/better-days': typeof BetterDaysRoute
  '/betterlife-episodes': typeof BetterlifeEpisodesRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/nairobby': typeof NairobbyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/this-is-life': typeof ThisIsLifeRoute
  '/this-is-life-episodes': typeof ThisIsLifeEpisodesRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/watch-them-all': typeof WatchThemAllRoute
  '/write-like-a-master': typeof WriteLikeAMasterRoute
  '/admin/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a-better-life': typeof ABetterLifeRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/back-to-us': typeof BackToUsRoute
  '/better-days': typeof BetterDaysRoute
  '/betterlife-episodes': typeof BetterlifeEpisodesRoute
  '/contact': typeof ContactRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/nairobby': typeof NairobbyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/this-is-life': typeof ThisIsLifeRoute
  '/this-is-life-episodes': typeof ThisIsLifeEpisodesRoute
  '/tv-shows': typeof TvShowsRoute
  '/watch-free': typeof WatchFreeRoute
  '/watch-them-all': typeof WatchThemAllRoute
  '/write-like-a-master': typeof WriteLikeAMasterRoute
  '/admin_/$section': typeof AdminSectionRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/episode/$slug/$episodeNumber': typeof EpisodeSlugEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/a-better-life'
    | '/about'
    | '/account'
    | '/admin'
    | '/back-to-us'
    | '/better-days'
    | '/betterlife-episodes'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/nairobby'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/this-is-life'
    | '/this-is-life-episodes'
    | '/tv-shows'
    | '/watch-free'
    | '/watch-them-all'
    | '/write-like-a-master'
    | '/admin/$section'
    | '/checkout/$productId'
    | '/payment/failed'
    | '/payment/success'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/a-better-life'
    | '/about'
    | '/account'
    | '/admin'
    | '/back-to-us'
    | '/better-days'
    | '/betterlife-episodes'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/nairobby'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/this-is-life'
    | '/this-is-life-episodes'
    | '/tv-shows'
    | '/watch-free'
    | '/watch-them-all'
    | '/write-like-a-master'
    | '/admin/$section'
    | '/checkout/$productId'
    | '/payment/failed'
    | '/payment/success'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/a-better-life'
    | '/about'
    | '/account'
    | '/admin'
    | '/back-to-us'
    | '/better-days'
    | '/betterlife-episodes'
    | '/contact'
    | '/movies'
    | '/my-list'
    | '/nairobby'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/this-is-life'
    | '/this-is-life-episodes'
    | '/tv-shows'
    | '/watch-free'
    | '/watch-them-all'
    | '/write-like-a-master'
    | '/admin_/$section'
    | '/checkout/$productId'
    | '/payment/failed'
    | '/payment/success'
    | '/title/$slug'
    | '/watch/$contentId'
    | '/episode/$slug/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ABetterLifeRoute: typeof ABetterLifeRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BackToUsRoute: typeof BackToUsRoute
  BetterDaysRoute: typeof BetterDaysRoute
  BetterlifeEpisodesRoute: typeof BetterlifeEpisodesRoute
  ContactRoute: typeof ContactRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  NairobbyRoute: typeof NairobbyRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ThisIsLifeRoute: typeof ThisIsLifeRoute
  ThisIsLifeEpisodesRoute: typeof ThisIsLifeEpisodesRoute
  TvShowsRoute: typeof TvShowsRoute
  WatchFreeRoute: typeof WatchFreeRoute
  WatchThemAllRoute: typeof WatchThemAllRoute
  WriteLikeAMasterRoute: typeof WriteLikeAMasterRoute
  AdminSectionRoute: typeof AdminSectionRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchContentIdRoute: typeof WatchContentIdRoute
  EpisodeSlugEpisodeNumberRoute: typeof EpisodeSlugEpisodeNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-better-life': {
      id: '/a-better-life'
      path: '/a-better-life'
      fullPath: '/a-better-life'
      preLoaderRoute: typeof ABetterLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-to-us': {
      id: '/back-to-us'
      path: '/back-to-us'
      fullPath: '/back-to-us'
      preLoaderRoute: typeof BackToUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/better-days': {
      id: '/better-days'
      path: '/better-days'
      fullPath: '/better-days'
      preLoaderRoute: typeof BetterDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betterlife-episodes': {
      id: '/betterlife-episodes'
      path: '/betterlife-episodes'
      fullPath: '/betterlife-episodes'
      preLoaderRoute: typeof BetterlifeEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nairobby': {
      id: '/nairobby'
      path: '/nairobby'
      fullPath: '/nairobby'
      preLoaderRoute: typeof NairobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-is-life': {
      id: '/this-is-life'
      path: '/this-is-life'
      fullPath: '/this-is-life'
      preLoaderRoute: typeof ThisIsLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-is-life-episodes': {
      id: '/this-is-life-episodes'
      path: '/this-is-life-episodes'
      fullPath: '/this-is-life-episodes'
      preLoaderRoute: typeof ThisIsLifeEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-free': {
      id: '/watch-free'
      path: '/watch-free'
      fullPath: '/watch-free'
      preLoaderRoute: typeof WatchFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-them-all': {
      id: '/watch-them-all'
      path: '/watch-them-all'
      fullPath: '/watch-them-all'
      preLoaderRoute: typeof WatchThemAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write-like-a-master': {
      id: '/write-like-a-master'
      path: '/write-like-a-master'
      fullPath: '/write-like-a-master'
      preLoaderRoute: typeof WriteLikeAMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$section': {
      id: '/admin_/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$contentId': {
      id: '/watch/$contentId'
      path: '/watch/$contentId'
      fullPath: '/watch/$contentId'
      preLoaderRoute: typeof WatchContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$slug/$episodeNumber': {
      id: '/episode/$slug/$episodeNumber'
      path: '/episode/$slug/$episodeNumber'
      fullPath: '/episode/$slug/$episodeNumber'
      preLoaderRoute: typeof EpisodeSlugEpisodeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ABetterLifeRoute: ABetterLifeRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BackToUsRoute: BackToUsRoute,
  BetterDaysRoute: BetterDaysRoute,
  BetterlifeEpisodesRoute: BetterlifeEpisodesRoute,
  ContactRoute: ContactRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  NairobbyRoute: NairobbyRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ThisIsLifeRoute: ThisIsLifeRoute,
  ThisIsLifeEpisodesRoute: ThisIsLifeEpisodesRoute,
  TvShowsRoute: TvShowsRoute,
  WatchFreeRoute: WatchFreeRoute,
  WatchThemAllRoute: WatchThemAllRoute,
  WriteLikeAMasterRoute: WriteLikeAMasterRoute,
  AdminSectionRoute: AdminSectionRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchContentIdRoute: WatchContentIdRoute,
  EpisodeSlugEpisodeNumberRoute: EpisodeSlugEpisodeNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
